import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "@/sass/main.scss";
import { connectToMongoDB } from "@/lib/mongodb";

const fontRoboto = Roboto({ subsets: ["latin"], weight: ["400", "500"], variable: '--font-roboto' });
const fontInter = Inter({ subsets: ["latin"], variable: '--font-inter' });

export const metadata: Metadata = {
  title: "Mangas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  connectToMongoDB();
  return (
    <html lang="en">
      <link rel="icon" href="/favicon/favicon.ico" sizes="any" />
      <body className={`${fontRoboto.variable} ${fontInter.variable}`}>{children}</body>
    </html>
  );
}
